import os
import sqlite3
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

# SQLite file path
DB_PATH = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "data", "audit_log.db")
)


class AuditLogCreate(BaseModel):
    session_id: str = Field(
        ..., description="Unique UUID to trace the query-to-feedback lifecycle"
    )
    query: str = Field(..., description="The original student/stakeholder inquiry")
    generated_draft: str = Field(
        ..., description="The draft response generated by the LLM"
    )
    subject: Optional[str] = Field(None, description="The original email subject line")
    sender: Optional[str] = Field(None, description="The original email sender")
    draft_subject: Optional[str] = Field(
        None, description="The drafted subject line response"
    )
    confidence: Optional[int] = Field(
        None, description="The computed RAG confidence score percentage"
    )
    pre_approved: Optional[bool] = Field(
        False, description="Flag indicating if the draft was automatically pre-approved"
    )
    channel: Optional[str] = Field(
        "portal", description="The communication channel: email, portal"
    )


class AuditLogUpdate(BaseModel):
    edited_response: Optional[str] = Field(
        None, description="The final response after admin review"
    )
    status: str = Field(..., description="Status of the ticket: approved, discarded")
    feedback_score: Optional[int] = Field(
        None, description="Feedback score: 1 for thumbs up, -1 for thumbs down"
    )
    feedback_comments: Optional[str] = Field(
        None, description="Optional text feedback detailing gaps"
    )


def init_db():
    """Initializes the SQLite database and creates/updates the audit_logs table."""
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id TEXT UNIQUE NOT NULL,
            query TEXT NOT NULL,
            generated_draft TEXT NOT NULL,
            edited_response TEXT,
            status TEXT DEFAULT 'generated',
            feedback_score INTEGER,
            feedback_comments TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)
    conn.commit()

    # Migration check: Check if new columns exist, and add them if missing
    cursor.execute("PRAGMA table_info(audit_logs)")
    columns = [row[1] for row in cursor.fetchall()]

    new_cols = {
        "subject": "TEXT",
        "sender": "TEXT",
        "draft_subject": "TEXT",
        "confidence": "INTEGER",
        "pre_approved": "INTEGER",
        "channel": "TEXT",
    }

    migration_done = False
    for col_name, col_type in new_cols.items():
        if col_name not in columns:
            cursor.execute(f"ALTER TABLE audit_logs ADD COLUMN {col_name} {col_type}")
            migration_done = True

    if migration_done:
        conn.commit()
    conn.close()


def create_audit_entry(log: AuditLogCreate) -> Dict[str, Any]:
    """Creates a new record in the audit log when a draft is first generated."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    now = datetime.now(timezone.utc).isoformat()
    pre_approved_val = 1 if log.pre_approved else 0
    try:
        cursor.execute(
            """
            INSERT INTO audit_logs (session_id, query, generated_draft, subject, sender, draft_subject, confidence, pre_approved, created_at, updated_at, channel)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                log.session_id,
                log.query,
                log.generated_draft,
                log.subject,
                log.sender,
                log.draft_subject,
                log.confidence,
                pre_approved_val,
                now,
                now,
                log.channel,
            ),
        )
        conn.commit()
    except sqlite3.IntegrityError:
        # If session_id already exists, update the fields
        cursor.execute(
            """
            UPDATE audit_logs 
            SET query = ?, generated_draft = ?, subject = ?, sender = ?, draft_subject = ?, confidence = ?, pre_approved = ?, updated_at = ?, channel = ?
            WHERE session_id = ?
            """,
            (
                log.query,
                log.generated_draft,
                log.subject,
                log.sender,
                log.draft_subject,
                log.confidence,
                pre_approved_val,
                now,
                log.channel,
                log.session_id,
            ),
        )
        conn.commit()

    conn.close()
    return get_audit_entry(log.session_id)


def update_audit_entry(session_id: str, update: AuditLogUpdate) -> Dict[str, Any]:
    """Updates an existing audit record with admin edits and feedback status."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()

    now = datetime.now(timezone.utc).isoformat()
    cursor.execute(
        """
        UPDATE audit_logs
        SET edited_response = ?, status = ?, feedback_score = ?, feedback_comments = ?, updated_at = ?
        WHERE session_id = ?
        """,
        (
            update.edited_response,
            update.status,
            update.feedback_score,
            update.feedback_comments,
            now,
            session_id,
        ),
    )
    conn.commit()
    conn.close()
    return get_audit_entry(session_id)


def get_audit_entry(session_id: str) -> Optional[Dict[str, Any]]:
    """Retrieves a single audit entry by its unique session ID."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM audit_logs WHERE session_id = ?", (session_id,))
    row = cursor.fetchone()
    conn.close()

    if row:
        return dict(row)
    return None


def get_all_audit_logs(limit: int = 100, offset: int = 0) -> List[Dict[str, Any]]:
    """Retrieves list of all audit logs for admin review and analytics."""
    init_db()
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM audit_logs ORDER BY created_at DESC LIMIT ? OFFSET ?",
        (limit, offset),
    )
    rows = cursor.fetchall()
    conn.close()
    return [dict(row) for row in rows]
